package com.silver_ads.teplo_tex_stroi.entity.fbDto;


import com.facebook.ads.sdk.AdsInsights;
import lombok.Data;
import javax.persistence.*;
import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "ads_statistics_fb")
public class AdsInsightsDTO {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(name = "date")
    private LocalDateTime date;
    @Column(name = "account_currency")
    private String mAccountCurrency = null;
    @Column(name = "account_id")
    private String mAccountId = null;
    @Column(name = "account_name")
    private String mAccountName = null;
    @Column(name = "ad_bid_type")
    private String mAdBidType = null;
    @Column(name = "ad_bid_value")
    private String mAdBidValue = null;
    @Column(name = "ad_delivery")
    private String mAdDelivery = null;
    @Column(name = "ad_id")
    private String mAdId = null;
    @Column(name = "ad_name")
    private String mAdName = null;
    @Column(name = "adset_bid_type")
    private String mAdsetBidType = null;
    @Column(name = "adset_bid_value")
    private String mAdsetBidValue = null;
    @Column(name = "adset_budget_type")
    private String mAdsetBudgetType = null;
    @Column(name = "adset_budget_value")
    private String mAdsetBudgetValue = null;
    @Column(name = "adset_delivery")
    private String mAdsetDelivery = null;
    @Column(name = "adset_end")
    private String mAdsetEnd = null;
    @Column(name = "adset_id")
    private String mAdsetId = null;
    @Column(name = "adset_name")
    private String mAdsetName = null;
    @Column(name = "adset_start")
    private String mAdsetStart = null;
    @Column(name = "age_targeting")
    private String mAgeTargeting = null;
    @Column(name = "attribution_setting")
    private String mAttributionSetting = null;
    @Column(name = "auction_bid")
    private String mAuctionBid = null;
    @Column(name = "auction_competitiveness")
    private String mAuctionCompetitiveness = null;
    @Column(name = "auction_max_competitor_bid")
    private String mAuctionMaxCompetitorBid = null;
    @Column(name = "buying_type")
    private String mBuyingType = null;
    @Column(name = "campaign_id")
    private String mCampaignId = null;
    @Column(name = "campaign_name")
    private String mCampaignName = null;
    @Column(name = "canvas_avg_view_percent")
    private String mCanvasAvgViewPercent = null;
    @Column(name = "canvas_avg_view_time")
    private String mCanvasAvgViewTime = null;
    @Column(name = "clicks")
    private String mClicks = null;
    @Column(name = "conversion_rate_ranking")
    private String mConversionRateRanking = null;
    @Column(name = "cost_per_dda_countby_convs")
    private String mCostPerDdaCountbyConvs = null;
    @Column(name = "cost_per_estimated_ad_recallers")
    private String mCostPerEstimatedAdRecallers = null;
    @Column(name = "cost_per_inline_link_click")
    private String mCostPerInlineLinkClick = null;
    @Column(name = "cost_per_inline_post_engagement")
    private String mCostPerInlinePostEngagement = null;
    @Column(name = "cost_per_unique_click")
    private String mCostPerUniqueClick = null;
    @Column(name = "cost_per_unique_inline_link_click")
    private String mCostPerUniqueInlineLinkClick = null;
    @Column(name = "cpc")
    private String mCpc = null;
    @Column(name = "cpm")
    private String mCpm = null;
    @Column(name = "cpp")
    private String mCpp = null;
    @Column(name = "created_time")
    private String mCreatedTime = null;
    @Column(name = "ctr")
    private String mCtr = null;
    @Column(name = "date_start")
    private String mDateStart = null;
    @Column(name = "date_stop")
    private String mDateStop = null;
    @Column(name = "dda_countby_convs")
    private String mDdaCountbyConvs = null;
    @Column(name = "engagement_rate_ranking")
    private String mEngagementRateRanking = null;
    @Column(name = "estimated_ad_recall_rate")
    private String mEstimatedAdRecallRate = null;
    @Column(name = "estimated_ad_recall_rate_lower_bound")
    private String mEstimatedAdRecallRateLowerBound = null;
    @Column(name = "estimated_ad_recall_rate_upper_bound")
    private String mEstimatedAdRecallRateUpperBound = null;
    @Column(name = "estimated_ad_recallers")
    private String mEstimatedAdRecallers = null;
    @Column(name = "estimated_ad_recallers_lower_bound")
    private String mEstimatedAdRecallersLowerBound = null;
    @Column(name = "estimated_ad_recallers_upper_bound")
    private String mEstimatedAdRecallersUpperBound = null;
    @Column(name = "frequency")
    private String mFrequency = null;
    @Column(name = "full_view_impressions")
    private String mFullViewImpressions = null;
    @Column(name = "full_view_reach")
    private String mFullViewReach = null;
    @Column(name = "gender_targeting")
    private String mGenderTargeting = null;
    @Column(name = "impressions")
    private String mImpressions = null;
    @Column(name = "inline_link_click_ctr")
    private String mInlineLinkClickCtr = null;
    @Column(name = "inline_link_clicks")
    private String mInlineLinkClicks = null;
    @Column(name = "inline_post_engagement")
    private String mInlinePostEngagement = null;
    @Column(name = "instant_experience_clicks_to_open")
    private String mInstantExperienceClicksToOpen = null;
    @Column(name = "instant_experience_clicks_to_start")
    private String mInstantExperienceClicksToStart = null;
    @Column(name = "instant_experience_outbound_clicks")
    private String mInstantExperienceOutboundClicks = null;
    @Column(name = "labels")
    private String mLabels = null;
    @Column(name = "location")
    private String mLocation = null;
    @Column(name = "objective")
    private String mObjective = null;
    @Column(name = "place_page_name")
    private String mPlacePageName = null;
    @Column(name = "qualifying_question_qualify_answer_rate")
    private String mQualifyingQuestionQualifyAnswerRate = null;
    @Column(name = "quality_ranking")
    private String mQualityRanking = null;
    @Column(name = "quality_score_ectr")
    private String mQualityScoreEctr = null;
    @Column(name = "quality_score_ecvr")
    private String mQualityScoreEcvr = null;
    @Column(name = "quality_score_organic")
    private String mQualityScoreOrganic = null;
    @Column(name = "reach")
    private String mReach = null;
    @Column(name = "social_spend")
    private String mSocialSpend = null;
    @Column(name = "spend")
    private String mSpend = null;
    @Column(name = "unique_clicks")
    private String mUniqueClicks = null;
    @Column(name = "unique_ctr")
    private String mUniqueCtr = null;
    @Column(name = "unique_inline_link_click_ctr")
    private String mUniqueInlineLinkClickCtr = null;
    @Column(name = "unique_inline_link_clicks")
    private String mUniqueInlineLinkClicks = null;
    @Column(name = "unique_link_clicks_ctr")
    private String mUniqueLinkClicksCtr = null;
    @Column(name = "updated_time")
    private String mUpdatedTime = null;
    @Column(name = "wish_bid")
    private String mWishBid = null;

    public AdsInsightsDTO() {
    }

    public AdsInsightsDTO fransformFrom(AdsInsights adsInsights) {
        this.mAccountCurrency = adsInsights.getFieldAccountCurrency();
        this.mAccountId = adsInsights.getFieldAccountId();
        this.mAccountName = adsInsights.getFieldAccountName();
        this.mAdBidType = adsInsights.getFieldAdBidType();
        this.mAdBidValue = adsInsights.getFieldAdBidValue();
        this.mAdDelivery = adsInsights.getFieldAdDelivery();
        this.mAdId = adsInsights.getFieldAdId();
        this.mAdName = adsInsights.getFieldAdName();
        this.mAdsetBidType = adsInsights.getFieldAdsetBidType();
        this.mAdsetBidValue = adsInsights.getFieldAdsetBidValue();
        this.mAdsetBudgetType = adsInsights.getFieldAdsetBudgetType();
        this.mAdsetBudgetValue = adsInsights.getFieldAdsetBudgetValue();
        this.mAdsetDelivery = adsInsights.getFieldAdsetDelivery();
        this.mAdsetEnd = adsInsights.getFieldAdsetEnd();
        this.mAdsetId = adsInsights.getFieldAdsetId();
        this.mAdsetName = adsInsights.getFieldAdsetName();
        this.mAdsetStart = adsInsights.getFieldAdsetStart();
        this.mAgeTargeting = adsInsights.getFieldAgeTargeting();
        this.mAttributionSetting = adsInsights.getFieldAttributionSetting();
        this.mAuctionBid = adsInsights.getFieldAuctionBid();
        this.mAuctionCompetitiveness = adsInsights.getFieldAuctionCompetitiveness();
        this.mAuctionMaxCompetitorBid = adsInsights.getFieldAuctionMaxCompetitorBid();
        this.mBuyingType = adsInsights.getFieldBuyingType();
        this.mCampaignId = adsInsights.getFieldCampaignId();
        this.mCampaignName = adsInsights.getFieldCampaignName();
        this.mCanvasAvgViewPercent = adsInsights.getFieldCanvasAvgViewPercent();
        this.mCanvasAvgViewTime = adsInsights.getFieldCanvasAvgViewTime();
        this.mClicks = adsInsights.getFieldClicks();
        this.mConversionRateRanking = adsInsights.getFieldConversionRateRanking();
        this.mCostPerDdaCountbyConvs = adsInsights.getFieldCostPerDdaCountbyConvs();
        this.mCostPerEstimatedAdRecallers = adsInsights.getFieldCostPerEstimatedAdRecallers();
        this.mCostPerInlineLinkClick = adsInsights.getFieldCostPerInlineLinkClick();
        this.mCostPerInlinePostEngagement = adsInsights.getFieldCostPerInlinePostEngagement();
        this.mCostPerUniqueClick = adsInsights.getFieldCostPerUniqueClick();
        this.mCostPerUniqueInlineLinkClick = adsInsights.getFieldCostPerUniqueInlineLinkClick();
        this.mCpc = adsInsights.getFieldCpc();
        this.mCpm = adsInsights.getFieldCpm();
        this.mCpp = adsInsights.getFieldCpp();
        this.mCreatedTime = adsInsights.getFieldCreatedTime();
        this.mCtr = adsInsights.getFieldCtr();
        this.mDateStart = adsInsights.getFieldDateStart();
        this.mDateStop = adsInsights.getFieldDateStop();
        this.mDdaCountbyConvs = adsInsights.getFieldDdaCountbyConvs();
        this.mEngagementRateRanking = adsInsights.getFieldEngagementRateRanking();
        this.mEstimatedAdRecallRate = adsInsights.getFieldEstimatedAdRecallRate();
        this.mEstimatedAdRecallRateLowerBound = adsInsights.getFieldEstimatedAdRecallRateLowerBound();
        this.mEstimatedAdRecallRateUpperBound = adsInsights.getFieldEstimatedAdRecallRateUpperBound();
        this.mEstimatedAdRecallers = adsInsights.getFieldEstimatedAdRecallers();
        this.mEstimatedAdRecallersLowerBound = adsInsights.getFieldEstimatedAdRecallersLowerBound();
        this.mEstimatedAdRecallersUpperBound = adsInsights.getFieldEstimatedAdRecallersUpperBound();
        this.mFrequency = adsInsights.getFieldFrequency();
        this.mFullViewImpressions = adsInsights.getFieldFullViewImpressions();
        this.mFullViewReach = adsInsights.getFieldFullViewReach();
        this.mGenderTargeting = adsInsights.getFieldGenderTargeting();
        this.mImpressions = adsInsights.getFieldImpressions();
        this.mInlineLinkClickCtr = adsInsights.getFieldInlineLinkClickCtr();
        this.mInlineLinkClicks = adsInsights.getFieldInlineLinkClicks();
        this.mInlinePostEngagement = adsInsights.getFieldInlinePostEngagement();
        this.mInstantExperienceClicksToOpen = adsInsights.getFieldInstantExperienceClicksToOpen();
        this.mInstantExperienceClicksToStart = adsInsights.getFieldInstantExperienceClicksToStart();
        this.mInstantExperienceOutboundClicks = adsInsights.getFieldInstantExperienceOutboundClicks();
        this.mLabels = adsInsights.getFieldLabels();
        this.mLocation = adsInsights.getFieldLocation();
        this.mObjective = adsInsights.getFieldObjective();
        this.mPlacePageName = adsInsights.getFieldPlacePageName();
        this.mQualifyingQuestionQualifyAnswerRate = adsInsights.getFieldQualifyingQuestionQualifyAnswerRate();
        this.mQualityRanking = adsInsights.getFieldQualityRanking();
        this.mQualityScoreEctr = adsInsights.getFieldQualityScoreEctr();
        this.mQualityScoreEcvr = adsInsights.getFieldQualityScoreEcvr();
        this.mQualityScoreOrganic = adsInsights.getFieldQualityScoreOrganic();
        this.mReach = adsInsights.getFieldReach();
        this.mSocialSpend = adsInsights.getFieldSocialSpend();
        this.mSpend = adsInsights.getFieldSpend();
        this.mUniqueClicks = adsInsights.getFieldUniqueClicks();
        this.mUniqueCtr = adsInsights.getFieldUniqueCtr();
        this.mUniqueInlineLinkClickCtr = adsInsights.getFieldUniqueInlineLinkClickCtr();
        this.mUniqueInlineLinkClicks = adsInsights.getFieldUniqueInlineLinkClicks();
        this.mUniqueLinkClicksCtr = adsInsights.getFieldUniqueLinkClicksCtr();
        this.mUpdatedTime = adsInsights.getFieldUpdatedTime();
        this.mWishBid = adsInsights.getFieldWishBid();

        return this;
    }
}
